# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Games",
            new_name="Game",
        ),
        migrations.RenameModel(
            old_name="Refs",
            new_name="Ref",
        ),
        migrations.RenameModel(
            old_name="Stats",
            new_name="Stat",
        ),
        migrations.RemoveField(
            model_name="player",
            name="password",
        ),
        migrations.RemoveField(
            model_name="player",
            name="user_name",
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(null=True, upload_to=b""),
        ),
    ]
