# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0002_auto_20170226_1432"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ref",
            old_name="plaer",
            new_name="player",
        ),
    ]
