# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20170227_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_regularseasion',
        ),
        migrations.AddField(
            model_name='game',
            name='is_postseason',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ref1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ref2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='division',
            field=models.CharField(choices=[(1, 'Sunday D1'), (2, 'Sunday D2'), (3, 'Wednesday Draft League')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='goals_against',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='goals_for',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='tie',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='win',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
