# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0005_auto_20170227_2323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="ref1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="leagues.Ref",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="ref2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="leagues.Ref",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.IntegerField(
                choices=[
                    (1980, 1980),
                    (1981, 1981),
                    (1982, 1982),
                    (1983, 1983),
                    (1984, 1984),
                    (1985, 1985),
                    (1986, 1986),
                    (1987, 1987),
                    (1988, 1988),
                    (1989, 1989),
                    (1990, 1990),
                    (1991, 1991),
                    (1992, 1992),
                    (1993, 1993),
                    (1994, 1994),
                    (1995, 1995),
                    (1996, 1996),
                    (1997, 1997),
                    (1998, 1998),
                    (1999, 1999),
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                ],
                default=2017,
                max_length=4,
            ),
        ),
    ]
