# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0007_auto_20170228_0733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="division",
            field=models.IntegerField(
                choices=[
                    (1, "Sunday D1"),
                    (2, "Sunday D2"),
                    (3, "Wednesday Draft League"),
                ],
                null=True,
            ),
        ),
    ]
