# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20170228_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
