# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0011_auto_20170301_1009"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.IntegerField(
                        choices=[
                            (1, "Sunday D1"),
                            (2, "Sunday D2"),
                            (3, "Wednesday Draft League"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team_Stat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("win", models.PositiveSmallIntegerField(default=0)),
                ("loss", models.PositiveSmallIntegerField(default=0)),
                ("tie", models.PositiveSmallIntegerField(default=0)),
                ("goals_for", models.PositiveSmallIntegerField(default=0)),
                ("goals_against", models.PositiveSmallIntegerField(default=0)),
                (
                    "division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leagues.Division",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="league",
            name="season",
        ),
        migrations.RemoveField(
            model_name="league",
            name="team",
        ),
        migrations.RemoveField(
            model_name="game",
            name="league",
        ),
        migrations.RemoveField(
            model_name="season",
            name="is_champion",
        ),
        migrations.RemoveField(
            model_name="season",
            name="team",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="league",
        ),
        migrations.AddField(
            model_name="stat",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Team",
            ),
        ),
        migrations.AlterField(
            model_name="roster",
            name="position2",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Center"), (2, "Wing"), (3, "Defense"), (4, "Goalie")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roster",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Team",
            ),
        ),
        migrations.DeleteModel(
            name="League",
        ),
        migrations.AddField(
            model_name="team_stat",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Season",
            ),
        ),
        migrations.AddField(
            model_name="team_stat",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Division",
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Division",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Division",
            ),
        ),
    ]
