# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0014_auto_20170302_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
