# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20170302_1919'),
    ]

    operations = [
		migrations.RenameModel(
            old_name='Game',
            new_name='Week',
        ),
        migrations.RenameField(
            model_name='Week',
            old_name='gamenumber',
            new_name='weeknumber',
        ),
        migrations.RenameField(
            model_name='MatchUp',
            old_name='game',
            new_name='week',
        ),
    ]

