# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20170303_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
