# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_auto_20170318_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('last_name',)},
        ),
    ]
