# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_auto_20170318_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ('week', 'time')},
        ),
    ]
