# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_auto_20170322_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ('team',)},
        ),
    ]
