# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0023_auto_20170323_0027"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchup",
            options={"ordering": ("week", "time")},
        ),
    ]
