# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0027_auto_20170323_1039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team_stat",
            options={"ordering": ("team__team_name",)},
        ),
        migrations.RenameField(
            model_name="week",
            old_name="weeknumber",
            new_name="game_number",
        ),
    ]
