# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_team_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.Roster'),
        ),
    ]
