# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-16 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0030_stat_roster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set([("team_name", "season")]),
        ),
    ]
