# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0031_auto_20170715_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.PositiveIntegerField(choices=[(1, 'East'), (2, 'West')], null=True),
        ),
    ]
