# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0032_team_conference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stat",
            name="division",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="roster",
        ),
        migrations.RemoveField(
            model_name="stat",
            name="season",
        ),
        migrations.AlterField(
            model_name="roster",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagues.Player",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.PositiveIntegerField(
                choices=[(1, "East"), (2, "West")], default=1, null=True
            ),
        ),
    ]
