# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0033_auto_20170728_1609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roster",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leagues.Player",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.PositiveIntegerField(
                choices=[(1, "East"), (2, "West")], null=True
            ),
        ),
    ]
