# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-30 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0034_auto_20170728_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.PositiveIntegerField(
                blank=True, choices=[(1, "East"), (2, "West")], null=True
            ),
        ),
    ]
