# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0036_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='/static/images/D1Champs.jpg', null=True, upload_to='teams'),
        ),
    ]
