# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0037_auto_20170901_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="photo",
            field=models.ImageField(
                default="/app/dcstreethockey/settings/../../media/D1Champs.jpg",
                null=True,
                upload_to="teams",
            ),
        ),
    ]
