# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0040_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='announcement1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='announcement2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='announcement3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
