# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0041_auto_20171009_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='twitter_posts',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
