# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-22 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0044_auto_20171222_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoMod',
            new_name='TeamPhoto',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='photoref',
            new_name='team_photo',
        ),
    ]
