# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-28 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0045_auto_20171222_1508"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="announcement3",
            new_name="announcement",
        ),
    ]
