# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-18 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0050_auto_20180702_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="alt_announcement3",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="alt_announcement4",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="alt_photo3",
            field=models.ImageField(blank=True, null=True, upload_to="homepage"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="alt_photo4",
            field=models.ImageField(blank=True, null=True, upload_to="homepage"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="alt_title3",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="alt_title4",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="winter_title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
