# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0054_auto_20200212_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="team_stat",
            name="otl",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
