# Generated by Django 3.0.7 on 2020-09-16 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0059_auto_20200904_1429"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchup",
            options={"ordering": ("-hometeam__season__year", "week", "time")},
        ),
    ]
