# Generated by Django 3.0.7 on 2020-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0060_auto_20200915_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='team_stat',
            options={'ordering': ('team__team_name', '-season__year')},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-season__year', '-game_number']},
        ),
        migrations.AlterField(
            model_name='matchup',
            name='time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_type',
            field=models.PositiveIntegerField(choices=[(1, 'Spring'), (2, 'Summer'), (3, 'Fall'), (4, 'Winter')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], db_index=True, default=2020),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(db_index=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='week',
            name='game_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
