# Generated by Django 3.1.6 on 2021-03-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0061_auto_20201006_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], db_index=True, default=2021),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='leagues_pla_last_na_a7929d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_name'], name='leagues_tea_team_na_8a0411_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['-season'], name='leagues_tea_season__9f9360_idx'),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['-game_number'], name='leagues_wee_game_nu_b321e6_idx'),
        ),
    ]
