# Generated by Django 3.1.8 on 2021-07-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0063_auto_20210318_2239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="division",
            field=models.IntegerField(
                choices=[
                    (1, "Sunday D1"),
                    (2, "Sunday D2"),
                    (3, "Wednesday Draft League"),
                    (4, "Monday Coed"),
                ],
                null=True,
                unique=True,
            ),
        ),
    ]
