# Generated by Django 3.1.8 on 2021-08-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0065_auto_20210722_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='teams')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.AddField(
            model_name='player',
            name='player_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.playerphoto'),
        ),
    ]
