# Generated by Django 3.1.8 on 2021-08-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0066_auto_20210816_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerphoto",
            name="photo",
            field=models.ImageField(blank=True, upload_to="players"),
        ),
    ]
