# Generated by Django 3.1.14 on 2022-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0070_auto_20220111_2032"),
    ]

    operations = [
        migrations.AddField(
            model_name="team_stat",
            name="otw",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
