# Generated by Django 3.1.14 on 2022-06-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0071_team_stat_otw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="division",
            field=models.IntegerField(
                choices=[
                    (1, "Sunday D1"),
                    (2, "Sunday D2"),
                    (3, "Wednesday Draft League"),
                    (4, "Monday Coed A League"),
                    (5, "Monday Coed B League"),
                ],
                null=True,
                unique=True,
            ),
        ),
    ]
