# Generated by Django 4.2.13 on 2024-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0075_auto_20240510_1543'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['player', 'team', 'matchup'], name='leagues_sta_player__daf39a_idx'),
        ),
    ]
