# Generated by Django 4.2.22 on 2025-07-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0078_alter_season_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="is_substitute",
            field=models.BooleanField(default=False),
        ),
    ]
