# Generated by Django 4.2.22 on 2025-12-30 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for all existing teams."""
    Team = apps.get_model("leagues", "Team")
    for team in Team.objects.all():
        team.captain_access_code = uuid.uuid4()
        team.save(update_fields=["captain_access_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0079_roster_is_substitute"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchup",
            name="away_goalie",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to use team's roster goalie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_goalie_matchups",
                to="leagues.player",
            ),
        ),
        migrations.AddField(
            model_name="matchup",
            name="away_goalie_status",
            field=models.PositiveIntegerField(
                choices=[(1, "Confirmed"), (2, "Sub Needed"), (3, "Unconfirmed")],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="matchup",
            name="home_goalie",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to use team's roster goalie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_goalie_matchups",
                to="leagues.player",
            ),
        ),
        migrations.AddField(
            model_name="matchup",
            name="home_goalie_status",
            field=models.PositiveIntegerField(
                choices=[(1, "Confirmed"), (2, "Sub Needed"), (3, "Unconfirmed")],
                default=3,
            ),
        ),
        # Step 1: Add field without unique constraint (nullable initially)
        migrations.AddField(
            model_name="team",
            name="captain_access_code",
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: Generate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_uuids, migrations.RunPython.noop),
        # Step 3: Make field non-nullable with unique constraint and default
        migrations.AlterField(
            model_name="team",
            name="captain_access_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
