# Generated by Django 4.2.22 on 2026-01-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0080_goalie_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="exclude_from_auto_deactivation",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this player won't be auto-deactivated by the cleanup command (e.g., available subs not on a roster)",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive players won't appear in goalie dropdowns",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                ],
                db_index=True,
                default=2026,
            ),
        ),
    ]
