# Generated by Django 4.2.22 on 2026-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0081_player_active_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="is_primary_goalie",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this goalie will be the default for goalie status pages. Only one goalie per team should be marked as primary.",
            ),
        ),
    ]
