# Generated by Django 4.2.22 on 2026-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0082_roster_primary_goalie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roster",
            name="player_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
