# Generated by Django 4.2.22 on 2026-01-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0083_alter_roster_player_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roster",
            name="is_primary_goalie",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If checked, this goalie will be the default for goalie status pages. Only one goalie per team should be marked as primary.",
            ),
        ),
        migrations.AlterField(
            model_name="roster",
            name="is_substitute",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="roster",
            name="position1",
            field=models.PositiveIntegerField(
                choices=[(1, "Center"), (2, "Wing"), (3, "Defense"), (4, "Goalie")],
                db_index=True,
            ),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(
                fields=["team", "position1"], name="leagues_ros_team_id_a76df8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(
                fields=["team", "is_primary_goalie"],
                name="leagues_ros_team_id_ea25b0_idx",
            ),
        ),
    ]
