# Generated by Django 4.2.22 on 2026-01-05 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0084_optimize_roster_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchUpGoalieStatus",
            fields=[],
            options={
                "verbose_name": "Goalie Status",
                "verbose_name_plural": "Goalie Statuses",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("leagues.matchup",),
        ),
    ]
