# Generated by Django 4.2.22 on 2026-02-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0085_matchupgoaliestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Check to mark all games for this division/date as cancelled. A banner will appear on the home page until the date passes.",
            ),
        ),
    ]
