# Generated by Django 4.2.22 on 2026-02-27 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0086_add_week_is_cancelled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="week",
            options={
                "ordering": ["-season__year", "-date"],
                "permissions": [
                    (
                        "can_quick_cancel_games",
                        "Can quick-cancel games from admin dashboard",
                    )
                ],
            },
        ),
    ]
