# Generated by Django 4.2.22 on 2026-03-27 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0087_week_quick_cancel_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("draw", "Draw Phase"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("complete", "Complete"),
                        ],
                        default="setup",
                        max_length=20,
                    ),
                ),
                ("num_teams", models.PositiveIntegerField(default=0)),
                ("num_rounds", models.PositiveIntegerField(default=0)),
                (
                    "commissioner_token",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "season",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_session",
                        to="leagues.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonSignup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "position_preference",
                    models.PositiveIntegerField(
                        choices=[(1, "Skater"), (2, "Goalie")], default=1
                    ),
                ),
                (
                    "is_returning",
                    models.BooleanField(
                        default=False,
                        help_text="Has this player played in the Wednesday Draft League before?",
                        verbose_name="Returning player?",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_player",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to existing player record to pull historical stats.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_signups",
                        to="leagues.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signups",
                        to="leagues.season",
                    ),
                ),
            ],
            options={
                "ordering": ("last_name", "first_name"),
                "unique_together": {("season", "first_name", "last_name")},
            },
        ),
        migrations.CreateModel(
            name="DraftTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to '{First Name}'s Team' if left blank.",
                        max_length=55,
                    ),
                ),
                ("draft_position", models.PositiveIntegerField(blank=True, null=True)),
                ("captain_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="captained_teams",
                        to="leagues.seasonsignup",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="leagues.draftsession",
                    ),
                ),
            ],
            options={
                "ordering": ("draft_position", "pk"),
                "unique_together": {("session", "captain")},
            },
        ),
        migrations.CreateModel(
            name="DraftRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("snake", "Snake (reverse of previous round)"),
                            ("randomized", "Re-randomized"),
                        ],
                        default="snake",
                        max_length=20,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="leagues.draftsession",
                    ),
                ),
            ],
            options={
                "ordering": ("round_number",),
                "unique_together": {("session", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="DraftPick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                (
                    "pick_number",
                    models.PositiveIntegerField(
                        help_text="Pick index within the round (0-based)."
                    ),
                ),
                ("picked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picks",
                        to="leagues.draftsession",
                    ),
                ),
                (
                    "signup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_pick",
                        to="leagues.seasonsignup",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_picks",
                        to="leagues.draftteam",
                    ),
                ),
            ],
            options={
                "ordering": ("round_number", "pick_number"),
                "unique_together": {
                    ("session", "signup"),
                    ("session", "round_number", "pick_number"),
                },
            },
        ),
    ]
