# Generated by Django 4.2.22 on 2026-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0088_draft_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftsession",
            name="signups_open",
            field=models.BooleanField(
                default=False,
                help_text="When checked, the public signup form is active for this season.",
            ),
        ),
    ]
