# Generated by Django 4.2.29 on 2026-04-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0093_draft_finalize_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seasonsignup",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="seasonsignup",
            name="notes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Out for travel, etc. beyond a random week or 2 that most miss.",
                max_length=500,
                verbose_name="Notes for the season",
            ),
        ),
    ]
