# Generated by Django 4.2.29 on 2026-04-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0094_remove_seasonsignup_unique_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=50)),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("commissioner", "Commissioner"),
                            ("captain", "Captain"),
                            ("spectator", "Spectator"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.CharField(max_length=500)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="leagues.draftsession",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftChatReaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=10)),
                ("sender_name", models.CharField(max_length=50)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="leagues.draftchatmessage",
                    ),
                ),
            ],
            options={
                "unique_together": {("message", "emoji", "sender_name")},
            },
        ),
    ]
