# Generated by Django 4.2.29 on 2026-04-20 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0095_draft_chat"),
        ("leagues", "0095_matchup_is_cancelled"),
    ]

    operations = []
