# Generated by Django 4.2.29 on 2026-04-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0096_merge_0095_draft_chat_0095_matchup_is_cancelled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPlayerPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="players/pending")),
                ("submitter_email", models.EmailField(blank=True, max_length=254)),
                ("submitter_note", models.CharField(blank=True, max_length=500)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_photos",
                        to="leagues.player",
                    ),
                ),
            ],
            options={
                "ordering": ("submitted_at",),
            },
        ),
    ]
