# Generated by Django 4.2.29 on 2026-04-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0097_pending_player_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="can_play_goalie",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this player appears in goalie sub dropdowns even if not rostered as a goalie (e.g. a player who occasionally fills in at goal).",
            ),
        ),
    ]
