# Generated by Django 4.2.30 on 2026-06-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0098_add_can_play_goalie_to_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchup",
            name="shootout_winner_is_home",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Set when a regular-season OT game is decided by shootout. True = home team won; False = away team won; null = no shootout.",
                null=True,
            ),
        ),
    ]
