# Generated by Django 4.2.30 on 2026-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0101_alter_division_id_alter_draftchatmessage_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonsignup",
            name="cell_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Used for game-day contact only.",
                max_length=20,
                verbose_name="Cell phone",
            ),
        ),
        migrations.AddField(
            model_name="seasonsignup",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "X-Large"),
                    ("XXL", "2X-Large"),
                    ("XXXL", "3X-Large"),
                ],
                default="",
                max_length=4,
                verbose_name="T-shirt size",
            ),
        ),
    ]
