# Generated by Django 5.2.16 on 2026-08-26 02:06

from django.db import migrations, models


def backfill_confirmed_captain(apps, schema_editor):
    """Existing captains (DraftTeam already exists) start checked, not blank."""
    SeasonSignup = apps.get_model("leagues", "SeasonSignup")
    DraftTeam = apps.get_model("leagues", "DraftTeam")
    captain_ids = DraftTeam.objects.values_list("captain_id", flat=True)
    SeasonSignup.objects.filter(pk__in=captain_ids).update(confirmed_captain=True)


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0102_seasonsignup_cell_phone_seasonsignup_tshirt_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonsignup",
            name="confirmed_captain",
            field=models.BooleanField(
                default=False,
                help_text="Set by commissioner. Creates or removes this signup's draft team.",
                verbose_name="Confirmed captain?",
            ),
        ),
        migrations.RunPython(backfill_confirmed_captain, migrations.RunPython.noop),
    ]
