# Generated by Django 5.2.16 on 2026-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0103_seasonsignup_confirmed_captain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_color",
            field=models.CharField(
                choices=[
                    ("Black", "Black"),
                    ("Blue", "Blue"),
                    ("Green", "Green"),
                    ("Grey", "Grey"),
                    ("Maroon", "Maroon"),
                    ("Orange", "Orange"),
                    ("Pink", "Pink"),
                    ("Purple", "Purple"),
                    ("Red", "Red"),
                    ("Teal", "Teal"),
                    ("White", "White"),
                    ("Yellow", "Yellow"),
                ],
                max_length=30,
            ),
        ),
    ]
